#!/usr/bin/env python3
"""Restore the Japanese retail title-logo blocks in an add00 container.

The Korean base rebuilt the title screen logo (``스ー퍼로봇대전 GC``) inside
the retail SPR topology: BMP9 atlas 3467 plus SCR maps 3469..3477 were
regenerated by ``build_jp_base_add00.py`` while palette 3468 stayed retail.
This tool puts the Japanese retail bytes back on exactly those blocks and
leaves every other block untouched, so the title screen shows the original
``スーパーロボット大戦GC`` art again.

Block lengths are allowed to differ between the source and the Japanese
reference; the outer absolute-offset table is recomputed with the same
logic the canvas-restore path uses.  (For the retail logo set all lengths
are in fact identical, so the table normally comes out byte-identical.)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS_DIR))
import add00_tools  # noqa: E402

from repack_preserve_indices import rebuild_container  # noqa: E402


DEFAULT_BLOCKS = (3467, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def parse_blocks(value: str) -> tuple[int, ...]:
    output: list[int] = []
    for part in value.split(","):
        part = part.strip()
        if "-" in part:
            start, end = part.split("-", 1)
            output.extend(range(int(start), int(end) + 1))
        elif part:
            output.append(int(part))
    if len(output) != len(set(output)):
        raise ValueError("duplicate block indices")
    return tuple(sorted(output))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Korean base add00")
    parser.add_argument("output", type=Path, help="title-restored add00")
    parser.add_argument("--japanese", type=Path, required=True, help="Japanese retail add00")
    parser.add_argument(
        "--blocks",
        type=parse_blocks,
        default=DEFAULT_BLOCKS,
        help="comma/range list of block indices to restore (default: title logo set)",
    )
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args(argv)

    source_path = args.source.expanduser().resolve()
    japanese_path = args.japanese.expanduser().resolve()
    output_path = args.output.expanduser().resolve()
    report_path = args.report.expanduser().resolve()
    if output_path in {source_path, japanese_path} or report_path in {
        source_path,
        japanese_path,
        output_path,
    }:
        raise ValueError("refusing to overwrite an input with the output or report")
    if output_path.exists() or report_path.exists():
        raise FileExistsError("output and report paths must not already exist")

    source = add00_tools.parse_container(source_path)
    japanese = add00_tools.parse_container(japanese_path)
    if len(source.blocks) != len(japanese.blocks):
        raise ValueError("container block counts differ")
    identity, _ = rebuild_container(list(source.blocks))
    if identity != source.source:
        raise RuntimeError("source container cannot be rebuilt byte-identically")

    restored: list[dict[str, object]] = []
    skipped: list[dict[str, object]] = []
    blocks = list(source.blocks)
    for index in args.blocks:
        if not 0 <= index < len(blocks):
            raise ValueError(f"block index out of range: {index}")
        record = {
            "block_index": index,
            "block_type": source.blocks[index][:4].hex(),
            "source_length": len(source.blocks[index]),
            "japanese_length": len(japanese.blocks[index]),
        }
        if source.blocks[index] == japanese.blocks[index]:
            skipped.append({**record, "reason": "already_japanese"})
            continue
        blocks[index] = japanese.blocks[index]
        restored.append(
            {
                **record,
                "source_sha256": sha256(source.blocks[index]),
                "japanese_sha256": sha256(japanese.blocks[index]),
            }
        )

    built, offsets = rebuild_container(blocks)
    verified = add00_tools.parse_container(built)
    if verified.offsets != offsets:
        raise RuntimeError("rebuilt offset table failed to parse")
    restored_indices = {int(row["block_index"]) for row in restored}
    changed = [
        index
        for index, (before, after) in enumerate(zip(source.blocks, verified.blocks))
        if before != after
    ]
    if sorted(restored_indices) != changed:
        raise RuntimeError(f"changed-block guard failed: {sorted(set(changed) ^ restored_indices)}")
    for index in restored_indices:
        if verified.blocks[index] != japanese.blocks[index]:
            raise RuntimeError(f"restored block {index} is not byte-identical to Japanese retail")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("xb") as handle:
        handle.write(built)

    report = {
        "schema": "srw-gc-add00-title-logo-jp-restore-v1",
        "status": "pass",
        "source": str(source_path),
        "source_sha256": sha256(source.source),
        "japanese_reference": str(japanese_path),
        "japanese_reference_sha256": sha256(japanese.source),
        "output": str(output_path),
        "output_sha256": sha256(built),
        "source_size": len(source.source),
        "output_size": len(built),
        "requested_blocks": list(args.blocks),
        "restored_blocks": sorted(restored_indices),
        "changed_blocks": changed,
        "restored": restored,
        "skipped": skipped,
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with report_path.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(
        json.dumps(
            {
                "output": report["output"],
                "output_sha256": report["output_sha256"],
                "restored_blocks": report["restored_blocks"],
                "status": report["status"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
